### ISSUE TITLE
Переменные окружения в .travis

### ISSUE THREAD

**Issue by ctrld** [Juev/juev.org#2]
У меня не сработали переменные окружения в env global для AWS S3 key/secret/bucket. Пришлось описывать переменные в web-интерфейсе проекта в Travis.
Ты тоже так сделал или переменные всё-таки работают?

**Comment by Juev** [comment]
Я пробовал сначала через веб-интерфейс, все работало. Но потом решил перенести в env global, и так же все работает.

Каждую переменную кодировал отдельно. При этом при кодировании задавал не только значение, но полностью все выражение. То есть прописывал:

    AWS_KEY=jksdfhjkhjksdf

Данное значение кодировал и добавлял в env global с приставкой secure.

**Comment by ctrld** [comment]
Ага, делал аналогично. Но что-то похоже недоделал. Или в Travis что-то не работает.

**Comment by Juev** [comment]
Опиши сам процесс, как ты и что делал, как прописывал. И что было в логах тревиса?

**Comment by ctrld** [comment]
Я делал так:
travis encrypt -r ctrld/ctrld.me S3_BUCKET=ctrld.me
потом вставлял результат по аналогии с тобой. Делал в билде "echo $S3_BUCKET" — пусто. Т.е. что-то не то.

**Comment by Juev** [comment]
Нет, я не использовал передачу параметров через командную строку. Я просто запускал:

    travis encrypt -r ctrld/ctrld.me

А если быть еще более точным, то я даже не передавал параметр -r, я просто запускал travis encrypt из корня локальной копии репозитория.

После чего попадал в режим редактирования, где и прописывал нужные мне выражения. По одному за раз.

**Comment by ctrld** [comment]
Спасибо, попробую.
